name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: windows-latest #allows for winforms to run

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies

      run: dotnet restore "Ecosystem Simulator.csproj"

    - name: Build

      run: dotnet build "Ecosystem Simulator.csproj" --no-restore

    - name: Test

      run: dotnet test "EcosystemSimulator.Tests/EcosystemSimulator.Tests.csproj" --no-build --verbosity normal